apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride | default .Release.Name }}
  labels:
    app: {{ .Values.nameOverride | default .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.nameOverride | default .Release.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nameOverride | default .Release.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Values.nameOverride | default .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.deployment.ports }}
        ports:
        {{- range .Values.deployment.ports }}
        - name: port-{{ . }}
          containerPort: {{ . }}
          protocol: TCP
        {{- end }}
        {{- end }}
        {{- if .Values.deployment.resources }}
        resources:
{{ toYaml .Values.deployment.resources | indent 10 }}
        {{- end }}
